// vertex shader - passes all attributes to fragment shader
void main
(
	float4 position : POSITION,
	float4 color : COLOR,
	float2 texcoord : TEXCOORD0,
	float4 sdfParams : TEXCOORD1,
	float4 sdfBorder : TEXCOORD2,
	out float4 oPosition : POSITION,
	out float4 oColor : COLOR,
	out float2 oTexcoord : TEXCOORD0,
	out float4 oSdfParams : TEXCOORD1,
	out float4 oSdfBorder : TEXCOORD2
)
{
	oPosition = position;
	oColor = color;
	oTexcoord = texcoord;
	oSdfParams = sdfParams;
	oSdfBorder = sdfBorder;
}
