using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SpritePacker
{
    // generates a C header with named sprite region definitions
    internal static class HeaderWriter
    {
        public static void Write(List<Sprite> sprites, string path)
        {
            string name = "spriteRegions";
            string guard = ToGuardName(Path.GetFileName(path));

            StringBuilder sb = new StringBuilder();
            sb.Append("#pragma once\r\n");
            sb.Append("\r\n");
            sb.Append("// auto-generated by sprite-packer - do not edit\r\n");
            sb.Append("\r\n");
            sb.Append("#include \"gfx.h\"\r\n");
            sb.Append("\r\n");

            // enum
            sb.Append("enum SpriteId {\r\n");
            for (int i = 0; i < sprites.Count; i++)
            {
                string comma = i < sprites.Count - 1 ? "," : "";
                sb.AppendFormat("    {0}{1}\r\n", ToEnumName(sprites[i].Name), comma);
            }
            sb.Append("};\r\n");
            sb.Append("\r\n");

            // table
            sb.AppendFormat("static const SpriteRegion {0}[{1}] = {{\r\n", name, sprites.Count);
            int maxNameLen = 0;
            foreach (Sprite s in sprites)
            {
                int len = ToEnumName(s.Name).Length;
                if (len > maxNameLen) maxNameLen = len;
            }
            foreach (Sprite s in sprites)
            {
                string enumName = ToEnumName(s.Name);
                sb.AppendFormat("    [{0}]{1} = {{ {2,4}, {3,4}, {4,4}, {5,4} }},\r\n",
                    enumName,
                    new string(' ', maxNameLen - enumName.Length),
                    s.X, s.Y, s.Width, s.Height);
            }
            sb.Append("};\r\n");
            sb.Append("\r\n");
            sb.Append("#define SPRITE_FULL ((SpriteRegion){0})\r\n");

            File.WriteAllText(path, sb.ToString());
        }

        private static string ToEnumName(string fileName)
        {
            StringBuilder sb = new StringBuilder("SPRITE_");
            foreach (char c in fileName.ToUpperInvariant())
            {
                if (c >= 'A' && c <= 'Z') sb.Append(c);
                else if (c >= '0' && c <= '9') sb.Append(c);
                else sb.Append('_');
            }
            return sb.ToString();
        }

        private static string ToGuardName(string fileName)
        {
            return ToEnumName(fileName).Replace("SPRITE_", "") + "_H";
        }
    }
}
