using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SpritePacker
{
   // generates a c header: an enum of sprite ids plus a SpriteRegion lookup table.
   internal static class HeaderWriter
   {
      public static void Write(List<Sprite> sprites, string path, string prefix = null)
      {
         string prefixName = prefix ?? "sprite";
         string tableName = prefixName + "Regions";
         string enumPrefix = prefixName.ToUpperInvariant() + "_";

         var builder = new StringBuilder();

         // file header
         builder.Append("#pragma once\r\n");
         builder.Append("\r\n");
         builder.Append("// auto-generated by sprite-packer - do not edit\r\n");
         builder.Append("\r\n");
         builder.Append("#include \"gfx.h\"\r\n");
         builder.Append("\r\n");

         // id enum, in packed order
         builder.AppendFormat("enum {0}Id {{\r\n", Capitalize(prefixName));
         for (int i = 0; i < sprites.Count; i++)
         {
            string comma = i < sprites.Count - 1 ? "," : "";
            builder.AppendFormat("    {0}{1}\r\n", ToEnumName(sprites[i].Name, enumPrefix), comma);
         }
         builder.Append("};\r\n");
         builder.Append("\r\n");

         // region table, with the names column padded to the longest entry
         builder.AppendFormat("static const SpriteRegion {0}[{1}] = {{\r\n", tableName, sprites.Count);
         int nameWidth = 0;
         foreach (Sprite sprite in sprites)
            nameWidth = Math.Max(nameWidth, ToEnumName(sprite.Name, enumPrefix).Length);
         foreach (Sprite sprite in sprites)
         {
            string enumName = ToEnumName(sprite.Name, enumPrefix);
            builder.AppendFormat("    [{0}]{1} = {{ {2,4}, {3,4}, {4,4}, {5,4} }},\r\n",
               enumName, new string(' ', nameWidth - enumName.Length), sprite.X, sprite.Y, sprite.Width, sprite.Height);
         }
         builder.Append("};\r\n");
         builder.Append("\r\n");
         builder.AppendFormat("#define {0}FULL ((SpriteRegion){{0}})\r\n", enumPrefix);

         File.WriteAllText(path, builder.ToString());
      }

      // turns a filename into an UPPER_SNAKE enum member: keep A-Z and 0-9, everything
      // else becomes '_', behind the given prefix (e.g. "new-file" -> "SPRITE_NEW_FILE").
      private static string ToEnumName(string fileName, string prefix)
      {
         var builder = new StringBuilder(prefix);
         foreach (char character in fileName.ToUpperInvariant())
         {
            bool keep = (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9');
            builder.Append(keep ? character : '_');
         }
         return builder.ToString();
      }

      private static string Capitalize(string text)
      {
         if (string.IsNullOrEmpty(text)) return text;
         return char.ToUpperInvariant(text[0]) + text.Substring(1);
      }
   }
}
