using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SpritePacker
{
    // generates a C header with named sprite region definitions
    internal static class HeaderWriter
    {
        public static void Write(List<Sprite> sprites, string path, string prefix = null)
        {
            string pfx = prefix ?? "sprite";
            string name = pfx + "Regions";
            string guard = ToGuardName(Path.GetFileName(path));

            StringBuilder sb = new StringBuilder();
            sb.Append("#pragma once\r\n");
            sb.Append("\r\n");
            sb.Append("// auto-generated by sprite-packer - do not edit\r\n");
            sb.Append("\r\n");
            sb.Append("#include \"gfx.h\"\r\n");
            sb.Append("\r\n");

            // enum
            string enumPrefix = pfx.ToUpperInvariant() + "_";
            sb.AppendFormat("enum {0}Id {{\r\n", Capitalize(pfx));
            for (int i = 0; i < sprites.Count; i++)
            {
                string comma = i < sprites.Count - 1 ? "," : "";
                sb.AppendFormat("    {0}{1}\r\n", ToEnumName(sprites[i].Name, enumPrefix), comma);
            }
            sb.Append("};\r\n");
            sb.Append("\r\n");

            // table
            sb.AppendFormat("static const SpriteRegion {0}[{1}] = {{\r\n", name, sprites.Count);
            int maxNameLen = 0;
            foreach (Sprite s in sprites)
            {
                int len = ToEnumName(s.Name, enumPrefix).Length;
                if (len > maxNameLen) maxNameLen = len;
            }
            foreach (Sprite s in sprites)
            {
                string enumName = ToEnumName(s.Name, enumPrefix);
                sb.AppendFormat("    [{0}]{1} = {{ {2,4}, {3,4}, {4,4}, {5,4} }},\r\n",
                    enumName,
                    new string(' ', maxNameLen - enumName.Length),
                    s.X, s.Y, s.Width, s.Height);
            }
            sb.Append("};\r\n");
            sb.Append("\r\n");
            sb.AppendFormat("#define {0}FULL ((SpriteRegion){{0}})\r\n", enumPrefix);

            File.WriteAllText(path, sb.ToString());
        }

        private static string ToEnumName(string fileName, string prefix)
        {
            StringBuilder sb = new StringBuilder(prefix);
            foreach (char c in fileName.ToUpperInvariant())
            {
                if (c >= 'A' && c <= 'Z') sb.Append(c);
                else if (c >= '0' && c <= '9') sb.Append(c);
                else sb.Append('_');
            }
            return sb.ToString();
        }

        private static string Capitalize(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            return char.ToUpperInvariant(s[0]) + s.Substring(1);
        }

        private static string ToGuardName(string fileName)
        {
            return ToEnumName(fileName, "").Replace("_", "") + "_H";
        }
    }
}
