using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace SpritePacker
{
   // generates the embedded icon-font byte array (.c) and the name->codepoint header (.h) from a Fontello
   // icons.ttf + config.json, so the icon set regenerates on build exactly like the sprite sheet does.
   internal static class IconFontWriter
   {
     private sealed class Glyph { public string Name; public int Code; }

     public static void Generate(string configPath, string ttfPath, string dataOutPath, string idsOutPath)
     {
       List<Glyph> glyphs = ParseConfig(File.ReadAllText(configPath));
       if (glyphs.Count == 0) throw new Exception("no glyphs found in " + configPath);

       WriteData(File.ReadAllBytes(ttfPath), dataOutPath);
       WriteIds(glyphs, idsOutPath);
       Console.WriteLine("generated {0} icons from {1}", glyphs.Count, Path.GetFileName(configPath));
     }

     // pulls each glyph's css name + codepoint from the Fontello config ("css" precedes "code" per entry).
     private static List<Glyph> ParseConfig(string json)
     {
       var glyphs = new List<Glyph>();
       MatchCollection matches = Regex.Matches(json, "\"css\"\\s*:\\s*\"([^\"]+)\".*?\"code\"\\s*:\\s*(\\d+)", RegexOptions.Singleline);
       foreach (Match match in matches)
         glyphs.Add(new Glyph { Name = match.Groups[1].Value, Code = int.Parse(match.Groups[2].Value) });
       return glyphs;
     }

     // emits: const unsigned char iconFontData[] = { ... }; const unsigned int iconFontDataSize = ...;
     private static void WriteData(byte[] bytes, string path)
     {
       var builder = new StringBuilder();
       builder.Append("// auto-generated by sprite-packer (icons mode) - do not edit.\r\n");
       builder.Append("// the icon-font logic (src/ui/icon-font.c) declares these two symbols extern.\r\n");
       builder.Append("\r\n");
       builder.Append("const unsigned char iconFontData[] = {\r\n");
       for (int i = 0; i < bytes.Length; i++)
       {
         if (i % 12 == 0) builder.Append("  ");
         builder.AppendFormat("0x{0:x2}", bytes[i]);
         if (i < bytes.Length - 1) builder.Append(",");
         builder.Append((i % 12 == 11 || i == bytes.Length - 1) ? "\r\n" : " ");
       }
       builder.Append("};\r\n");
       builder.Append("const unsigned int iconFontDataSize = sizeof(iconFontData);\r\n");
       File.WriteAllText(path, builder.ToString());
     }

     // emits: typedef enum { ICON_X = 0x.., ... } IconId;  (names padded so the '=' column lines up)
     private static void WriteIds(List<Glyph> glyphs, string path)
     {
       // two css names can collapse to the same ICON_ identifier (e.g. "file-audio" / "file_audio"), which
       // would emit a duplicate C enum member with a cryptic compiler error - catch it here with a clear one.
       var seen = new Dictionary<string, string>();
       foreach (Glyph glyph in glyphs)
       {
         string name = ToEnumName(glyph.Name);
         string other;
         if (seen.TryGetValue(name, out other))
            throw new Exception("duplicate icon id " + name + " from css '" + other + "' and '" + glyph.Name + "'");
         seen[name] = glyph.Name;
       }

       var builder = new StringBuilder();
       builder.Append("#pragma once\r\n");
       builder.Append("\r\n");
       builder.Append("// auto-generated by sprite-packer (icons mode) from icons/config.json - do not edit.\r\n");
       builder.Append("// one entry per glyph in the embedded icon font; the value is the font's codepoint. See ui/icon-font.h.\r\n");
       builder.Append("\r\n");
       builder.Append("#include <stdint.h>\r\n");
       builder.Append("\r\n");
       builder.Append("typedef enum {\r\n");

       int nameWidth = 0;
       foreach (Glyph glyph in glyphs)
         nameWidth = Math.Max(nameWidth, ToEnumName(glyph.Name).Length);
       for (int i = 0; i < glyphs.Count; i++)
       {
         string name = ToEnumName(glyphs[i].Name);
         string comma = i < glyphs.Count - 1 ? "," : "";
         builder.AppendFormat("   {0}{1} = 0x{2:X4}{3}\r\n", name, new string(' ', nameWidth - name.Length), glyphs[i].Code, comma);
       }
       builder.Append("} IconId;\r\n");
       File.WriteAllText(path, builder.ToString());
     }

     // css name -> ICON_UPPER_SNAKE (same rule as the sprite enum): keep A-Z / 0-9, everything else '_'.
     private static string ToEnumName(string css)
     {
       var builder = new StringBuilder("ICON_");
       foreach (char character in css.ToUpperInvariant())
       {
         bool keep = (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9');
         builder.Append(keep ? character : '_');
       }
       return builder.ToString();
     }
   }
}
