#pragma once

// auto-generated by sprite-packer - do not edit

#include "gfx.h"

enum SpriteId {
   SPRITE_SPEAKER
};

static const SpriteRegion spriteRegions[1] = {
   [SPRITE_SPEAKER] = {    0,    0,   32,   29 },
};

#define SPRITE_FULL ((SpriteRegion){0})
