// play screen - resolve a video, then stream it with the simple-lib-av engine.
//
// Both stream urls are handed straight to the player: simple-lib-av opens each through
// openHttpStream (the http module), so each demuxer reads the moov and then each sample
// on demand by HTTP range - nothing is downloaded in full. Adaptive picks are split: a
// video-only stream plus an audio-only stream, each its own independent http stream.
//
// Follows file-manager's video overlay: the open work runs on a worker
// (createVideoPlayer does blocking network I/O and must stay off the UI thread),
// the UI thread adopts the built player and pulls frames each render frame.

#include "screens/play.h"
#include "extractor.h"
#include "stream-select.h"   // pickBestVideo / pickBestAudio (shared with download)

#include "gfx.h"
#include "colors.h"
#include "pad.h"
#include "font.h"
#include "ui/label.h"
#include "ui/volume-meter.h"
#include "sprite-regions.h"     // generated by sprite-packer (speaker icon)
#include "button-repeat.h"     // left/right scrub auto-repeat
#include "thread.h"
#include "screen-manager.h"
#include "string-utilities.h"   // strCopy

#include "video-player.h"
#include "audio.h"              // setAudioPcmFeedVolume
#include "storage.h"            // resume position (get/setWatchedPosition)
#include "sponsorblock.h"       // skip segments (auto-skip + seek-bar marks)
#include "subtitles.h"          // fetch + parse a caption track; cue lookup during playback
#include "chapters.h"           // description timestamp lines -> chapter list
#include "dbg.h"                // logInfo/logError (bridge)

#include <string.h>
#include <stdlib.h>
#include <stdio.h>              // snprintf (stats overlay)
#include <sys/sys_time.h>       // sys_time_get_system_time (fps measure)

// volume: up/down step the shared pill meter (ui/volume-meter.h), pills in youtube red.
#define VOLUME_DEFAULT    12
#define COLOR_PILL_FILL   0xFFFF0000u   // youtube red, matches the seek-bar fill

// seek controls (bar + time) show on activity / pause, then auto-hide. left/right scrub the target
// instantly; the engine seek (a decoder flush + fragment reload each time) fires once input goes quiet.
#define SEEK_STEP_SECONDS   5.0f
#define SEEK_APPLY_IDLE_US  400000ULL
#define CONTROLS_VISIBLE_US 3000000ULL
#define TOAST_VISIBLE_US    2000000ULL   // how long a toast ("Skipped ...", "Subtitles: ...") stays up

// subtitles: triangle cycles off -> track 1 -> track 2 -> ... -> off; the active cue draws above the
// seek bar, and the HUD shows the chosen language top-right while the controls are up.
#define SUBTITLE_TEXT_SIZE 30

// description overlay: SELECT toggles the description full-screen; up/down scroll it.
#define DESCRIPTION_MARGIN_X    120
#define DESCRIPTION_MARGIN_Y    80
#define DESCRIPTION_TEXT_SIZE   24
#define DESCRIPTION_SCROLL_STEP 40

// chapter picker: START toggles a centred list of the video's chapters; up/down select
// (the window follows the selection), cross jumps there, circle/START close without jumping.
#define CHAPTER_TEXT_SIZE    24
#define CHAPTER_ROW_HEIGHT   46
#define CHAPTER_VISIBLE_ROWS 12
#define CHAPTER_TIME_GAP     24   // between the right-aligned time column and the title column

// the video to play, set by playVideo() before the screen is pushed. defaults to
// a short public clip so pushing the screen directly still does something.
static char requestedInput[256] = "jNQXAC9IVRw";   // "Me at the zoo"

typedef enum { STAGE_LOADING, STAGE_FAILED, STAGE_PLAYING } Stage;

static struct {
   volatile Stage   stage;
   char             message[128];     // failure reason (worker writes, UI reads)
   VideoPlayer     *pendingPlayer;    // built by the worker, adopted by the UI thread
   volatile int     workerDone;
   int              threadActive;
   sys_ppu_thread_t workerTid;
   VideoPlayer     *player;
   int              screenW, screenH;
   int              firstFrameSeen;   // a real frame has been presented (loading status ends, save is safe)
   int              showStats;        // R3 toggles a debug overlay
   char             title[256];        // resolved video title (worker sets, UI reads after adoption)
   char             description[2048]; // resolved video description (worker sets, UI reads after adoption)

   // description overlay: the text is rasterised once, on first open, into one tall texture that
   // up/down scroll. playback carries on untouched underneath.
   int              descriptionVisible;
   int              descriptionRendered;
   int              descriptionScroll;   // pixels scrolled down into the text

   // chapter picker: chapters come out of the description at resolve time; when that finds none, a
   // side worker asks the /next endpoint (YouTube's own chapter list). the row labels are rasterised
   // on first open, and the widest row sizes the panel.
   ChapterList      chapters;            // parsed by the worker (UI reads after adoption)
   ChapterList      fetchedChapters;     // /next result (worker writes, copied over on reap)
   volatile int     chWorkerDone;
   int              chThreadActive, chFetchTried;
   sys_ppu_thread_t chWorkerTid;
   int              chaptersVisible;
   int              chaptersRendered;
   int              chapterSelected;
   int              chapterTimeWidth;    // widest time label (the right-aligned time column)
   int              chapterPanelWidth;
   int              vidItag, vidW, vidH, vidFps, audItag;   // picked formats (worker sets, UI reads)
   int              isLive;           // a live stream: no duration, no resume/save, no seek
   const uint8_t   *lastFrame;        // fps measure: a changed pointer means a newly presented frame
   int              framesThisSecond, measuredFps;
   uint64_t         fpsTickUs;

   // seek: the UI owns the scrub target so the bar moves instantly; the engine seek is deferred until
   // the input goes quiet (each apply costs a decoder flush + fragment reload)
   int              seeking;
   float            seekTarget;
   uint64_t         lastSeekInputUs;
   uint64_t         controlsShownUs;   // last activity, for the bar/time auto-hide

   // sponsorblock: fetched on a side thread (in parallel with resolve/open), then auto-skipped during
   // playback and drawn on the seek bar. sbReady goes up once the thread is reaped and segments are safe.
   SponsorSegments  sb;
   volatile int     sbWorkerDone;
   int              sbThreadActive, sbReady;
   sys_ppu_thread_t sbWorkerTid;
   uint64_t         toastShownUs;      // brief toast timer (0 = hidden)

   // subtitles: triangle picks a track (-1 = off, the default); a worker fetches it in the background
   // (updatePlay respawns the fetch whenever the pick and the fetched track disagree), and once ready
   // the cue for the current position drives subtitleLabel each frame.
   CaptionTrack     captionTracks[MAX_CAPTION_TRACKS];   // copied from the resolve (worker sets)
   int              captionCount;
   int              subtitlePick;        // chosen track index, -1 = off
   int              subtitleFetched;     // track index the fetch (in flight or done) belongs to, -1 = none
   int              subtitlesReady;      // fetched track is safe to read
   int              subtitleScanFrom;    // cue lookup cache (getSubtitleCueText)
   SubtitleTrack   *subtitleTrack;       // heap; ~800 KB, allocated on first enable, freed on exit
   volatile int     subWorkerDone;
   int              subThreadActive;
   sys_ppu_thread_t subWorkerTid;
} state;

#define STAT_LINES 4

static Font  font;
static Label statusLabel;
static Label statLabels[STAT_LINES];
static Label timeLeftLabel, timeRightLabel;   // seek bar: current time (left) / total (right)
static Label toastLabel;                      // brief centred toast ("Skipped ...", "Subtitles: ...")
static Label titleLabel;                      // video title, top-left while the seek bar is up
static Label subtitleLabel;                   // active subtitle cue, above the seek bar
static Label subsHudLabel;                    // chosen subtitle language, top-right while the HUD is up
static Label chapterLabels[MAX_CHAPTERS];     // chapter titles (picker overlay rows)
static Label chapterTimeLabels[MAX_CHAPTERS]; // chapter start times, right-aligned in their own column
static TextTexture descriptionTexture;        // whole description as one tall texture (scrolled by draw)

// the shared pill meter; its level is kept in `volumeLevel` outside `state` so it survives across videos.
static VolumeMeter volumeMeter;
static int volumeLevel = VOLUME_DEFAULT;

// the packed sprite sheet, loaded once for the app's lifetime (only the speaker icon lives in it)
static GfxTexture spriteSheet;
static int spriteSheetLoadTried;
static uint64_t playRequestUs;   // TEMP: set when the user picks a video, to time the WHOLE select->picture path

static void fail(const char *reason)
{
   logError("[yt] play failed: %s\n", reason);
   strCopy(state.message, sizeof state.message, reason);
   __sync_synchronize();   // publish message before the UI thread sees STAGE_FAILED
   state.stage = STAGE_FAILED;
}

// only languages FONT_POP renders reliably (hardware-checked: western/central europe + japanese fine,
// vietnamese diacritics broken). prefix match, so "en-GB" passes as "en". extend after testing a new
// language on the console.
static int isRenderableSubtitleLanguage(const char *code)
{
   static const char *supported[] = { "en", "es", "pt", "fr", "de", "it", "nl", "sv", "da", "no", "fi",
                                      "pl", "cs", "sk", "hu", "ro", "tr", "id", "ms", "ja" };
   for (int i = 0; i < (int)(sizeof supported / sizeof *supported); i++)
      if (strncmp(code, supported[i], strlen(supported[i])) == 0) return 1;
   return 0;
}

static void worker(uint64_t arg)
{
   (void)arg;
   uint64_t tPlayStart = sys_time_get_system_time();   // TEMP: full resume-path timing (resolve -> open -> seek)
   logInfo("[yt] diag worker started %llums after select\n", (unsigned long long)((tPlayStart - playRequestUs) / 1000));   // TEMP
   StreamInfo *info = malloc(sizeof *info);   // ~50 KB, too big for the stack
   const Extractor *extractor = findExtractor(requestedInput);
   if (!info || !extractor) { fail("unrecognised link or id"); goto done; }

   // resolve (stage stays STAGE_LOADING, set by initPlay's memset, until we adopt or fail)
   if (extractor->extract(requestedInput, info) != 0 || info->formatCount == 0) { fail("resolve failed"); goto done; }
   strCopy(state.title, sizeof state.title, info->title);
   strCopy(state.description, sizeof state.description, info->description);
   parseChapters(state.description, &state.chapters);
   for (int i = 0; i < info->captionCount; i++)   // keep only tracks the system font can render
      if (isRenderableSubtitleLanguage(info->captions[i].languageCode))
         state.captionTracks[state.captionCount++] = info->captions[i];
   logInfo("[yt] diag resolve took %llums\n", (unsigned long long)((sys_time_get_system_time() - tPlayStart) / 1000));   // TEMP

   const StreamFormat *video = pickBestVideo(info);
   if (!video) { fail("no playable mp4 video"); goto done; }
   // a muxed pick (itag 18) already carries audio; a video-only pick needs a separate audio track
   const StreamFormat *audio = video->hasAudio ? NULL : pickBestAudio(info);
   logInfo("[yt] play video itag %d %dx%d %s, audio itag %d\n", video->itag, video->width, video->height,
           video->hasAudio ? "muxed" : "video-only", audio ? audio->itag : (video->hasAudio ? video->itag : 0));

   state.vidItag = video->itag; state.vidW = video->width; state.vidH = video->height; state.vidFps = video->fps;
   state.audItag = audio ? audio->itag : (video->hasAudio ? video->itag : 0);
   state.isLive = video->isLiveSegmented;

   // open the decoder: both streams ride the http module by range request. an audio open
   // failure inside the player just means silent playback. NULL if it can't be demuxed/decoded.
   uint64_t tBeforeOpen = sys_time_get_system_time();   // TEMP
   state.pendingPlayer = createVideoPlayerSplit(video->url, audio ? audio->url : NULL, allocGfxVideoBuffer, freeGfxVideoBuffer);
   if (!state.pendingPlayer) { fail("couldn't open stream"); goto done; }
   logInfo("[yt] diag open both streams took %llums (total since play %llums)\n",   // TEMP
           (unsigned long long)((sys_time_get_system_time() - tBeforeOpen) / 1000),
           (unsigned long long)((sys_time_get_system_time() - tPlayStart) / 1000));

   // resume where we left off. seekVideoPlayer only posts the target; the decode thread does the
   // reconnect + fragment reload. drawPlay keeps the "Loading..." status up until the first frame is
   // presented, so that reload is covered rather than showing a black screen. storage returns 0 for a
   // typed url (never a history key), so this no-ops for anything but a bare videoId.
   {
      int resumeAt = state.isLive ? 0 : getWatchedPosition(requestedInput);
      float duration = getVideoDurationSeconds(state.pendingPlayer);
      if (resumeAt > 3 && (duration <= 0 || resumeAt < duration - 10)) seekVideoPlayer(state.pendingPlayer, (float)resumeAt);
   }

done:
   free(info);
   __sync_synchronize();
   state.workerDone = 1;
   exitThread();
}

// a bare 11-char videoId (not a typed url) is what SponsorBlock and history key on; typed urls no-op.
static int isBareVideoId(const char *input)
{
   return input[0] && !strchr(input, '/') && !strchr(input, ':');
}

// fetch skip segments in parallel with resolve/open, so they cost no startup latency.
static void sponsorWorker(uint64_t arg)
{
   (void)arg;
   fetchSponsorSegments(requestedInput, &state.sb);
   __sync_synchronize();
   state.sbWorkerDone = 1;
   exitThread();
}

// asks /next for youtube's own chapter list; spawned only when the description parse found none.
static void chapterWorker(uint64_t arg)
{
   (void)arg;
   fetchChapters(requestedInput, &state.fetchedChapters);
   __sync_synchronize();
   state.chWorkerDone = 1;
   exitThread();
}

void playVideo(const char *input)
{
   strCopy(requestedInput, sizeof requestedInput, input);
   playRequestUs = sys_time_get_system_time();   // TEMP: start of the true perceived resume
   pushScreen(&playScreen);
}

static void initPlay(void)
{
   memset(&state, 0, sizeof state);
   state.screenW = getGfxScreenWidth();
   state.screenH = getGfxScreenHeight();

   font = openSystemFont(FONT_POP);
   initLabel(&statusLabel, &font, 0, 0, 1400, AUTO, 28, COLOR_SLATE_100, TEXT_NOWRAP, "");
   for (int i = 0; i < STAT_LINES; i++)
      initLabel(&statLabels[i], &font, 0, 0, 600, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");
   initLabel(&timeLeftLabel,  &font, 0, 0, 200, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");
   initLabel(&timeRightLabel, &font, 0, 0, 200, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");
   initLabelRaw(&toastLabel, &font, 0, 0, 400, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");   // raw: shows track names
   initLabelRaw(&titleLabel, &font, 0, 0, 1100, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP_ELLIPSIS, "");
   initLabelRaw(&subtitleLabel, &font, 0, 0, 1600, AUTO, SUBTITLE_TEXT_SIZE, COLOR_SLATE_100, TEXT_WRAP, "");
   initLabelRaw(&subsHudLabel, &font, 0, 0, 500, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP_ELLIPSIS, "");
   for (int i = 0; i < MAX_CHAPTERS; i++) {
      initLabelRaw(&chapterLabels[i], &font, 0, 0, 990, AUTO, CHAPTER_TEXT_SIZE, COLOR_SLATE_100, TEXT_NOWRAP_ELLIPSIS, "");
      initLabel(&chapterTimeLabels[i], &font, 0, 0, 150, AUTO, CHAPTER_TEXT_SIZE, COLOR_SLATE_400, TEXT_NOWRAP, "");
   }
   state.subtitlePick = state.subtitleFetched = -1;   // default off (memset left them 0)

   if (!spriteSheetLoadTried) {
      spriteSheetLoadTried = 1;
      spriteSheet = loadGfxTexture("/dev_hdd0/game/YOPLAYER1/USRDIR/sprites.png");
      if (spriteSheet.w == 0) logWarn("[yt] sprite sheet missing, no speaker icon\n");
   }
   initVolumeMeter(&volumeMeter, &font, spriteSheet, spriteRegions[SPRITE_SPEAKER], COLOR_PILL_FILL, volumeLevel);
   layoutVolumeMeter(&volumeMeter, state.screenW, state.screenH);

   state.threadActive = (spawnJoinableThread(&state.workerTid, worker, 0,
                         THREAD_PRIORITY_DEFAULT, THREAD_STACK_SIZE_64KB, "yt-play") == 0);
   if (!state.threadActive) fail("couldn't start worker");

   if (isBareVideoId(requestedInput))
      state.sbThreadActive = (spawnJoinableThread(&state.sbWorkerTid, sponsorWorker, 0,
                              THREAD_PRIORITY_DEFAULT, THREAD_STACK_SIZE_64KB, "yt-sponsor") == 0);
}

static void showControls(void) { state.controlsShownUs = sys_time_get_system_time(); }

static void formatTime(char *buffer, int cap, int seconds)
{
   if (seconds < 0) seconds = 0;
   if (seconds >= 3600) snprintf(buffer, cap, "%d:%02d:%02d", seconds / 3600, (seconds % 3600) / 60, seconds % 60);
   else                 snprintf(buffer, cap, "%d:%02d", seconds / 60, seconds % 60);
}

static void showToast(const char *text)
{
   setLabelText(&toastLabel, text);
   state.toastShownUs = sys_time_get_system_time();
   showControls();
}

static void changeVolume(int delta)
{
   volumeLevel = stepVolumeMeter(&volumeMeter, delta);
   setAudioPcmFeedVolume(getVolumeMeterFraction(&volumeMeter));
}

// fetches the picked caption track in the background; updatePlay reaps it and respawns on a new pick.
static void subtitleWorker(uint64_t arg)
{
   (void)arg;
   fetchSubtitles(state.captionTracks[state.subtitleFetched].url, state.subtitleTrack);   // a failure leaves count 0
   __sync_synchronize();
   state.subWorkerDone = 1;
   exitThread();
}

// triangle: cycle off -> track 1 -> ... -> off; the pick shows in the top-right HUD badge. the fetch
// itself is driven by updatePlay, so a mid-fetch switch just supersedes the old pick.
static void cycleSubtitles(void)
{
   // live captions use a rolling delivery our fetcher can't parse, so live streams count as none
   if (state.captionCount == 0 || state.isLive) { showToast("No subtitles"); return; }
   state.subtitlePick = state.subtitlePick + 1 < state.captionCount ? state.subtitlePick + 1 : -1;

   setLabelText(&subtitleLabel, "");   // clear the old track's cue; the new one repopulates once fetched

   char hud[64];
   if (state.subtitlePick < 0) strCopy(hud, sizeof hud, "Subtitles: Off");
   else snprintf(hud, sizeof hud, "Subtitles: %s", state.captionTracks[state.subtitlePick].name);
   setLabelText(&subsHudLabel, hud);
   showControls();
}

// accumulates a scrub target while left/right is held; the engine seek fires once input goes quiet
static void nudgeSeek(float deltaSeconds, uint64_t nowUs)
{
   if (!state.seeking) { state.seeking = 1; state.seekTarget = getVideoPositionSeconds(state.player); }
   state.seekTarget += deltaSeconds;
   float duration = getVideoDurationSeconds(state.player);
   if (state.seekTarget < 0.0f) state.seekTarget = 0.0f;
   if (duration > 0.0f && state.seekTarget > duration) state.seekTarget = duration;
   state.lastSeekInputUs = nowUs;
   showControls();
}

// left/right scrub, cross toggles pause (restarts if the video ended). only once playing.
static void handlePlaybackInput(void)
{
   uint64_t nowUs = sys_time_get_system_time();

   if (isPadButtonPressed(PAD_BTN_CROSS)) {
      if (isVideoEnded(state.player)) seekVideoPlayer(state.player, 0.0f);
      else setVideoPaused(state.player, !isVideoPaused(state.player));
      showControls();
   }

   if (isPadButtonPressed(PAD_BTN_TRIANGLE)) cycleSubtitles();

   // volume: stepped, with auto-repeat while held (works on live streams too)
   static ButtonRepeat volumeRepeat;
   if (isRepeatDue(&volumeRepeat, getPadButtonState(PAD_BTN_UP)))        changeVolume(+1);
   else if (isRepeatDue(&volumeRepeat, getPadButtonState(PAD_BTN_DOWN))) changeVolume(-1);

   if (state.isLive) return;   // a live stream has no seek index; scrubbing would break the segment stream

   static ButtonRepeat seekRepeat;
   if (isRepeatDue(&seekRepeat, getPadButtonState(PAD_BTN_RIGHT)))     nudgeSeek(+SEEK_STEP_SECONDS, nowUs);
   else if (isRepeatDue(&seekRepeat, getPadButtonState(PAD_BTN_LEFT))) nudgeSeek(-SEEK_STEP_SECONDS, nowUs);

   if (state.seeking && nowUs - state.lastSeekInputUs >= SEEK_APPLY_IDLE_US) {
      seekVideoPlayer(state.player, state.seekTarget);
      state.seeking = 0;
   }
}

// jump past the first not-yet-skipped sponsor segment the playhead has entered. one-shot per segment so a
// manual rewind into it doesn't fight the user.
static void autoSkipSponsor(void)
{
   float pos = getVideoPositionSeconds(state.player);
   for (int i = 0; i < state.sb.count; i++) {
      SponsorSegment *segment = &state.sb.segments[i];
      if (segment->skipped || pos < segment->start || pos >= segment->end - 0.2f) continue;
      segment->skipped = 1;
      seekVideoPlayerPast(state.player, segment->end);   // land on the next keyframe after the segment, not before it
      char notice[64];
      snprintf(notice, sizeof notice, "Skipped %s", getSponsorCategoryName(segment->category));
      showToast(notice);
      return;
   }
}

// SELECT opens the description: rasterise the text once, off the draw path, as one tall wrapped
// texture the draw scrolls through. playback carries on untouched underneath.
static void openDescription(void)
{
   if (!state.descriptionRendered) {
      renderFontRaw(&descriptionTexture, &font, DESCRIPTION_TEXT_SIZE, state.description[0] ? state.description : "No description.",
                    COLOR_SLATE_100, state.screenW - 2 * DESCRIPTION_MARGIN_X, TEXT_WRAP);
      state.descriptionRendered = 1;
   }
   state.descriptionScroll = 0;
   state.descriptionVisible = 1;
}

// while the description is up it owns the pad: SELECT/circle close it, up/down scroll. playback
// input (seek, pause, back-out) is blocked underneath.
static void handleDescriptionInput(void)
{
   if (isPadButtonPressed(PAD_BTN_SELECT) || isPadButtonPressed(PAD_BTN_CIRCLE)) {
      state.descriptionVisible = 0;
      return;
   }

   static ButtonRepeat scrollRepeat;
   if (isRepeatDue(&scrollRepeat, getPadButtonState(PAD_BTN_DOWN)))    state.descriptionScroll += DESCRIPTION_SCROLL_STEP;
   else if (isRepeatDue(&scrollRepeat, getPadButtonState(PAD_BTN_UP))) state.descriptionScroll -= DESCRIPTION_SCROLL_STEP;

   int viewHeight = state.screenH - 2 * DESCRIPTION_MARGIN_Y;
   int maxScroll = descriptionTexture.tex.h > viewHeight ? descriptionTexture.tex.h - viewHeight : 0;
   if (state.descriptionScroll > maxScroll) state.descriptionScroll = maxScroll;
   if (state.descriptionScroll < 0) state.descriptionScroll = 0;
}

// START opens the chapter picker: the rows are rasterised once (off the draw path), the widest time
// and title size the two columns, and the selection starts on the chapter the playhead is in.
static void openChapters(void)
{
   // live streams can't seek, so a chapter jump has nowhere to go even if the description lists times
   if (state.chapters.count == 0 || state.isLive) { showToast("No chapters"); return; }

   if (!state.chaptersRendered) {
      int widestTitle = 0;
      for (int i = 0; i < state.chapters.count; i++) {
         char timeText[16];
         formatTime(timeText, sizeof timeText, (int)state.chapters.chapters[i].start);
         setLabelText(&chapterTimeLabels[i], timeText);
         setLabelText(&chapterLabels[i], state.chapters.chapters[i].title);
         if (chapterTimeLabels[i].tt.tex.w > state.chapterTimeWidth) state.chapterTimeWidth = chapterTimeLabels[i].tt.tex.w;
         if (chapterLabels[i].tt.tex.w > widestTitle) widestTitle = chapterLabels[i].tt.tex.w;
      }
      state.chapterPanelWidth = state.chapterTimeWidth + CHAPTER_TIME_GAP + widestTitle;
      state.chaptersRendered = 1;
   }

   float position = getVideoPositionSeconds(state.player);
   state.chapterSelected = 0;
   for (int i = 0; i < state.chapters.count; i++)
      if (state.chapters.chapters[i].start <= position) state.chapterSelected = i;
   state.chaptersVisible = 1;
}

// while the picker is up it owns the pad: up/down move the selection, cross jumps to the chapter
// (playback carries on paused or playing, only the position moves), circle/START close without
// jumping. playback input is blocked underneath.
static void handleChaptersInput(void)
{
   if (isPadButtonPressed(PAD_BTN_CIRCLE) || isPadButtonPressed(PAD_BTN_START)) { state.chaptersVisible = 0; return; }

   if (isPadButtonPressed(PAD_BTN_CROSS)) {
      state.chaptersVisible = 0;
      state.seeking = 0;   // a pending scrub must not overwrite the jump
      seekVideoPlayer(state.player, state.chapters.chapters[state.chapterSelected].start);
      showControls();
      return;
   }

   static ButtonRepeat navigateRepeat;
   if (isRepeatDue(&navigateRepeat, getPadButtonState(PAD_BTN_DOWN)))    state.chapterSelected++;
   else if (isRepeatDue(&navigateRepeat, getPadButtonState(PAD_BTN_UP))) state.chapterSelected--;
   if (state.chapterSelected < 0) state.chapterSelected = 0;
   if (state.chapterSelected >= state.chapters.count) state.chapterSelected = state.chapters.count - 1;
}

static void updatePlay(void)
{
   // an overlay owns the pad for the whole frame it was (or just became) visible, so the button that
   // closed or opened it can't leak into playback input below (e.g. cross toggling pause on the way out)
   int overlayHadPad = state.descriptionVisible || state.chaptersVisible;
   if (state.descriptionVisible) handleDescriptionInput();
   else if (state.chaptersVisible) handleChaptersInput();
   else {
      if (isPadButtonPressed(PAD_BTN_CIRCLE)) { popScreen(); return; }   // back to the results list
      if (isPadButtonPressed(PAD_BTN_R3)) state.showStats = !state.showStats;
      if (isPadButtonPressed(PAD_BTN_SELECT) && state.stage == STAGE_PLAYING && state.player) openDescription();
      if (isPadButtonPressed(PAD_BTN_START) && state.stage == STAGE_PLAYING && state.player) openChapters();
   }

   // reap the worker once it's done; adopt the player it built
   if (state.workerDone && state.threadActive) {
      joinThread(state.workerTid);
      state.threadActive = 0;
      if (state.pendingPlayer) {
         state.player = state.pendingPlayer;
         state.pendingPlayer = NULL;
         setAudioPcmFeedVolume(getVolumeMeterFraction(&volumeMeter));
         setLabelText(&titleLabel, state.title);   // rasterise once, off the draw path
         state.stage = STAGE_PLAYING;
      }
   }

   // reap the sponsorblock fetch; its segments are safe to read once joined
   if (state.sbWorkerDone && state.sbThreadActive) {
      joinThread(state.sbWorkerTid);
      state.sbThreadActive = 0;
      state.sbReady = 1;
   }

   // chapters: when the description parse found none, ask /next once for youtube's own list
   if (state.stage == STAGE_PLAYING && !state.chFetchTried && state.chapters.count == 0 && !state.isLive &&
       isBareVideoId(requestedInput)) {
      state.chFetchTried = 1;
      state.chThreadActive = (spawnJoinableThread(&state.chWorkerTid, chapterWorker, 0,
                              THREAD_PRIORITY_DEFAULT, THREAD_STACK_SIZE_64KB, "yt-chapters") == 0);
   }
   if (state.chWorkerDone && state.chThreadActive) {
      joinThread(state.chWorkerTid);
      state.chThreadActive = 0;
      state.chapters = state.fetchedChapters;   // safe to adopt now the worker is reaped
   }

   // subtitles: reap a finished fetch (stale if the pick moved mid-fetch), then start one whenever
   // the pick and the fetched track disagree
   if (state.subWorkerDone && state.subThreadActive) {
      joinThread(state.subWorkerTid);
      state.subThreadActive = 0;
      state.subtitlesReady = (state.subtitleFetched == state.subtitlePick);
      if (!state.subtitlesReady) state.subtitleFetched = -1;   // pick moved mid-fetch: re-picking must refetch
      else if (state.subtitleTrack->count == 0) {   // fetch failed or empty track: drop to Off, visibly
         state.subtitlePick = state.subtitleFetched = -1;
         state.subtitlesReady = 0;
         setLabelText(&subsHudLabel, "Subtitles: Off");
         showToast("Subtitles unavailable");
      }
   }
   if (state.subtitlePick >= 0 && state.subtitlePick != state.subtitleFetched && !state.subThreadActive) {
      if (!state.subtitleTrack) state.subtitleTrack = malloc(sizeof *state.subtitleTrack);
      if (state.subtitleTrack) {
         state.subtitlesReady = 0;
         state.subtitleScanFrom = 0;
         state.subWorkerDone = 0;
         state.subtitleFetched = state.subtitlePick;
         state.subThreadActive = (spawnJoinableThread(&state.subWorkerTid, subtitleWorker, 0,
                                  THREAD_PRIORITY_DEFAULT, THREAD_STACK_SIZE_64KB, "yt-subs") == 0);
         if (!state.subThreadActive) state.subtitleFetched = -1;   // spawn failed: retry next frame
      }
   }

   // feed the cue covering the current position into the label; setLabelText only rasterises on change
   if (state.subtitlesReady && state.subtitlePick >= 0 && state.stage == STAGE_PLAYING && state.player)
      setLabelText(&subtitleLabel, getSubtitleCueText(state.subtitleTrack, getVideoPositionSeconds(state.player), &state.subtitleScanFrom));

   if (state.stage == STAGE_PLAYING && state.player && !overlayHadPad && !state.descriptionVisible && !state.chaptersVisible)
      handlePlaybackInput();
   if (state.sbReady && state.stage == STAGE_PLAYING && state.player && !isVideoPaused(state.player) && !state.seeking)
      autoSkipSponsor();

   // status text: the failure reason, or "Loading..." until playback. setLabelText skips unchanged
   // text, so calling it each frame only rasterises on a real change.
   if (state.stage == STAGE_FAILED) setLabelText(&statusLabel, state.message);
   else if (state.stage != STAGE_PLAYING) setLabelText(&statusLabel, "Loading...");
}

// fits w x h inside the screen preserving aspect ratio; returns the centred rect.
static void letterboxRect(int w, int h, int *dx, int *dy, int *dw, int *dh)
{
   float frameAspect  = (float)w / (float)h;
   float screenAspect = (float)state.screenW / (float)state.screenH;
   if (frameAspect > screenAspect) { *dw = state.screenW; *dh = (int)(state.screenW / frameAspect); }
   else                            { *dh = state.screenH; *dw = (int)(state.screenH * frameAspect); }
   *dx = (state.screenW - *dw) / 2;
   *dy = (state.screenH - *dh) / 2;
}

// measure the real presented frame rate: a changed frame pointer is a new frame; tally them per second.
static void measureFps(const uint8_t *frame)
{
   if (frame && frame != state.lastFrame) { state.framesThisSecond++; state.lastFrame = frame; }
   uint64_t now = sys_time_get_system_time();
   if (now - state.fpsTickUs >= 1000000) { state.measuredFps = state.framesThisSecond; state.framesThisSecond = 0; state.fpsTickUs = now; }
}

// rebuild the overlay lines. setLabelText skips unchanged text, so calling this per frame only
// rasterises when a value actually moves (fps + time once a second).
static void updateStatLabels(void)
{
   char line[96];
   int rate = 0, channels = 0;
   getAudioTrackInfo(state.player, &rate, &channels);
   float pos = getVideoPositionSeconds(state.player), duration = getVideoDurationSeconds(state.player);

   snprintf(line, sizeof line, "Video  itag %d   %dx%d   H.264", state.vidItag, state.vidW, state.vidH);
   setLabelText(&statLabels[0], line);
   snprintf(line, sizeof line, "FPS  %d   (target %d)", state.measuredFps, state.vidFps);
   setLabelText(&statLabels[1], line);
   if (state.audItag) snprintf(line, sizeof line, "Audio  itag %d   AAC %d Hz   %d ch", state.audItag, rate, channels);
   else               strCopy(line, sizeof line, "Audio  none");
   setLabelText(&statLabels[2], line);
   snprintf(line, sizeof line, "Time  %d:%02d / %d:%02d", (int)pos / 60, (int)pos % 60, (int)duration / 60, (int)duration % 60);
   setLabelText(&statLabels[3], line);
}

static void drawStatsOverlay(void)
{
   int x = 40, y = 44, lineHeight = 30;
   fillGfxRectangle(x - 14, y - 12, 500, STAT_LINES * lineHeight + 14, 0xC0000000);
   for (int i = 0; i < STAT_LINES; i++) drawLabelAt(&statLabels[i], x, y + i * lineHeight);
}

// seek bar + time show while scrubbing / paused / ended, else auto-hide after the last activity
static int controlsVisible(void)
{
   if (isVideoPaused(state.player) || isVideoEnded(state.player) || state.seeking) return 1;
   return state.controlsShownUs != 0 && sys_time_get_system_time() - state.controlsShownUs < CONTROLS_VISIBLE_US;
}

// paint each sponsor segment onto the bar in its category colour, over the progress fill so it stays
// visible in the already-watched region (as YouTube's SponsorBlock overlay does).
static void drawSponsorSegments(int barLeft, int span, int barTopY, int barH, float duration)
{
   if (duration <= 0.0f) return;
   for (int i = 0; i < state.sb.count; i++) {
      const SponsorSegment *segment = &state.sb.segments[i];
      float startFrac = segment->start / duration, endFrac = segment->end / duration;
      if (startFrac < 0.0f) startFrac = 0.0f;
      if (endFrac > 1.0f) endFrac = 1.0f;
      int segX = barLeft + (int)(startFrac * span);
      int segW = (int)((endFrac - startFrac) * span);
      if (segW < 2) segW = 2;
      fillGfxRectangle(segX, barTopY, segW, barH, getSponsorCategoryColor(segment->category));
   }
}

// a red YouTube-style progress bar low on the screen with current/total time on each side, drawn from
// plain rectangles (no spritesheet), with sponsor segments marked over the fill.
static void drawSeekBar(void)
{
   float duration = getVideoDurationSeconds(state.player);
   float position = state.seeking ? state.seekTarget : getVideoPositionSeconds(state.player);
   float progress = duration > 0.0f ? position / duration : 0.0f;
   if (progress < 0.0f) progress = 0.0f;
   if (progress > 1.0f) progress = 1.0f;

   int barLeft  = (int)(state.screenW * 0.24f);
   int barRight = state.screenW - barLeft;
   int span     = barRight - barLeft;
   int barY     = (int)(state.screenH * 0.94f);
   int barH     = 8;
   int barTopY  = barY - barH / 2;
   int filledW  = (int)(progress * span);

   fillGfxRectangle(barLeft, barTopY, span, barH, 0x66FFFFFF);            // track
   fillGfxRectangle(barLeft, barTopY, filledW, barH, 0xFFFF0000);        // progress (youtube red)
   if (state.sbReady) drawSponsorSegments(barLeft, span, barTopY, barH, duration);
   if (duration > 0.0f)   // chapter boundaries notch the bar, youtube-style
      for (int i = 1; i < state.chapters.count; i++)
         fillGfxRectangle(barLeft + (int)(state.chapters.chapters[i].start / duration * span), barTopY, 3, barH, 0xFF000000);
   fillGfxRectangle(barLeft + filledW - 3, barY - 11, 6, 22, 0xFFFFFFFF);   // scrubber handle

   char text[16];
   formatTime(text, sizeof text, (int)position);            setLabelText(&timeLeftLabel, text);
   formatTime(text, sizeof text, (int)(duration + 0.5f));   setLabelText(&timeRightLabel, text);
   drawLabelAt(&timeLeftLabel,  barLeft - 20 - timeLeftLabel.tt.tex.w, barY - timeLeftLabel.tt.tex.h / 2);
   drawLabelAt(&timeRightLabel, barRight + 20, barY - timeRightLabel.tt.tex.h / 2);
}

// a top-of-screen HUD badge in the thumbnails' duration-tag style: label on a translucent black box,
// with breathing room either side so the text never touches the box edges.
#define BADGE_PAD_X 14

static void drawBadge(Label *label, int x, int y)
{
   fillGfxRectangle(x, y, label->tt.tex.w + 2 * BADGE_PAD_X, label->tt.tex.h + 8, 0xCC000000);
   drawLabelAt(label, x + BADGE_PAD_X, y + 4);
}

// title top-left + chosen subtitle language top-right, shown whenever the seek bar is up.
static void drawTitle(void)
{
   if (titleLabel.tt.tex.w > 0) drawBadge(&titleLabel, 40, 32);
}

static void drawSubsHud(void)
{
   if (subsHudLabel.tt.tex.w > 0) drawBadge(&subsHudLabel, state.screenW - 40 - (subsHudLabel.tt.tex.w + 2 * BADGE_PAD_X), 32);
}

// the active subtitle cue, centred above the seek bar on a dim backdrop.
static void drawSubtitle(void)
{
   if (state.subtitlePick < 0 || subtitleLabel.tt.tex.w == 0) return;
   int x = state.screenW / 2 - subtitleLabel.tt.tex.w / 2;
   int y = (int)(state.screenH * 0.94f) - 40 - subtitleLabel.tt.tex.h;
   fillGfxRectangle(x - 12, y - 6, subtitleLabel.tt.tex.w + 24, subtitleLabel.tt.tex.h + 12, 0xA0000000);
   drawLabelAt(&subtitleLabel, x, y);
}

// the description over the whole video: a semi-transparent black layer, then the slice of the text
// texture the scroll position selects (the texture is drawn through a window, so no clipping is needed).
static void drawDescription(void)
{
   fillGfxRectangle(0, 0, state.screenW, state.screenH, 0xD9000000);   // 85% opaque black
   if (descriptionTexture.tex.w == 0) return;

   int viewHeight = state.screenH - 2 * DESCRIPTION_MARGIN_Y;
   int visibleHeight = descriptionTexture.tex.h - state.descriptionScroll;
   if (visibleHeight > viewHeight) visibleHeight = viewHeight;
   if (visibleHeight <= 0) return;

   float sliceTop    = (float)state.descriptionScroll / descriptionTexture.tex.h;
   float sliceBottom = (float)(state.descriptionScroll + visibleHeight) / descriptionTexture.tex.h;
   drawGfxTexture(DESCRIPTION_MARGIN_X, DESCRIPTION_MARGIN_Y, descriptionTexture.tex.w, visibleHeight,
                  descriptionTexture.tex, 0.0f, sliceTop, 1.0f, sliceBottom, 0xFFFFFFFF, GFX_FILTER_NEAREST);
}

// the chapter picker: a dim layer, then a centred column of rows windowed around the selection;
// the selected row gets a subtle highlight with a youtube-red accent on its left edge.
static void drawChapters(void)
{
   fillGfxRectangle(0, 0, state.screenW, state.screenH, 0xD9000000);   // 85% opaque black

   // window the rows around the selection so long lists stay reachable without a scrollbar
   int rows = state.chapters.count < CHAPTER_VISIBLE_ROWS ? state.chapters.count : CHAPTER_VISIBLE_ROWS;
   int firstRow = state.chapterSelected - rows / 2;
   if (firstRow > state.chapters.count - rows) firstRow = state.chapters.count - rows;
   if (firstRow < 0) firstRow = 0;

   int panelX = state.screenW / 2 - state.chapterPanelWidth / 2;
   int titleX = panelX + state.chapterTimeWidth + CHAPTER_TIME_GAP;
   int topY   = state.screenH / 2 - rows * CHAPTER_ROW_HEIGHT / 2;

   for (int row = 0; row < rows; row++) {
      int index = firstRow + row;
      int rowY  = topY + row * CHAPTER_ROW_HEIGHT;
      if (index == state.chapterSelected) {
         fillGfxRectangle(panelX - 19, rowY, state.chapterPanelWidth + 43, CHAPTER_ROW_HEIGHT, 0x28FFFFFF);
         fillGfxRectangle(panelX - 24, rowY, 5, CHAPTER_ROW_HEIGHT, 0xFFFF0000);   // red accent, flush with the highlight
      }
      drawLabelAt(&chapterTimeLabels[index], panelX + state.chapterTimeWidth - chapterTimeLabels[index].tt.tex.w,
                  getCenteredLabelY(&chapterTimeLabels[index], rowY, CHAPTER_ROW_HEIGHT));
      drawLabelAt(&chapterLabels[index], titleX, getCenteredLabelY(&chapterLabels[index], rowY, CHAPTER_ROW_HEIGHT));
   }
}

// a brief toast in the top-right notification spot, one badge row below the subtitle-language badge.
static void drawToast(void)
{
   if (state.toastShownUs == 0 || sys_time_get_system_time() - state.toastShownUs >= TOAST_VISIBLE_US) return;
   drawBadge(&toastLabel, state.screenW - 40 - (toastLabel.tt.tex.w + 2 * BADGE_PAD_X), 80);
}

static void drawPlay(void)
{
   fillGfxRectangle(0, 0, state.screenW, state.screenH, COLOR_BLACK);   // letterbox bars read as black, not slate

   const uint8_t *frame = NULL;
   if (state.player) {
      int w, h;
      frame = getVideoFrame(state.player, &w, &h);
      if (frame) {
         if (!state.firstFrameSeen) {
            logInfo("[yt] diag select-to-picture %llums\n", (unsigned long long)((sys_time_get_system_time() - playRequestUs) / 1000));   // TEMP
            showControls();   // bring the HUD (seek bar + title) up as playback starts; it auto-hides as usual
         }
         state.firstFrameSeen = 1;
         int dx, dy, dw, dh;
         letterboxRect(w, h, &dx, &dy, &dw, &dh);
         drawGfxYuvFrame(dx, dy, dw, dh, frame, w, h);
      }
      measureFps(frame);
      if (state.showStats && frame) { updateStatLabels(); drawStatsOverlay(); }
      int overlayUp = state.chaptersVisible || state.descriptionVisible;   // a full-screen overlay hides the HUD noise
      if (state.stage == STAGE_PLAYING && !state.isLive && controlsVisible() && !overlayUp)   // live has no timeline
         { drawSeekBar(); drawTitle(); drawSubsHud(); }
      if (state.stage == STAGE_PLAYING && !overlayUp) { drawSubtitle(); drawToast(); drawVolumeMeter(&volumeMeter); }
      if (state.chaptersVisible) drawChapters();
      if (state.descriptionVisible) drawDescription();
   }

   // until the first frame is presented (open, then the async resume seek's reload) keep the loading
   // status up instead of a black screen; with no player this shows the failure message.
   if (!state.firstFrameSeen)
      drawLabelAt(&statusLabel, state.screenW / 2 - statusLabel.tt.tex.w / 2, state.screenH / 2 - 14);
}

static void termPlay(void)
{
   if (state.threadActive) { joinThread(state.workerTid); state.threadActive = 0; }
   if (state.sbThreadActive) { joinThread(state.sbWorkerTid); state.sbThreadActive = 0; }   // usually already done
   if (state.subThreadActive) { joinThread(state.subWorkerTid); state.subThreadActive = 0; }
   if (state.chThreadActive) { joinThread(state.chWorkerTid); state.chThreadActive = 0; }
   free(state.subtitleTrack);
   state.subtitleTrack = NULL;
   // save the resume position on the way out; a finished video is saved as 0 so it restarts next time.
   // only once a frame has actually played: a failed open or a resume seek that never landed must not
   // clobber a good saved position with 0. storage ignores non-id keys, so typed urls no-op.
   if (state.player && state.firstFrameSeen && !state.isLive)
      setWatchedPosition(requestedInput, isVideoEnded(state.player) ? 0 : (int)getVideoPositionSeconds(state.player));
   if (state.player || state.pendingPlayer) finishGfx();   // RSX may still be sampling a frame buffer
   if (state.player) { destroyVideoPlayer(state.player); state.player = NULL; }
   if (state.pendingPlayer) { destroyVideoPlayer(state.pendingPlayer); state.pendingPlayer = NULL; }
   freeLabel(&statusLabel);
   for (int i = 0; i < STAT_LINES; i++) freeLabel(&statLabels[i]);
   freeLabel(&timeLeftLabel);
   freeLabel(&timeRightLabel);
   freeLabel(&toastLabel);
   freeLabel(&titleLabel);
   freeLabel(&subtitleLabel);
   freeLabel(&subsHudLabel);
   for (int i = 0; i < MAX_CHAPTERS; i++) { freeLabel(&chapterLabels[i]); freeLabel(&chapterTimeLabels[i]); }
   freeVolumeMeter(&volumeMeter);
   freeTextTexture(&descriptionTexture);
   closeFont(&font);
}

Screen playScreen = { initPlay, NULL, updatePlay, drawPlay, NULL, termPlay, SCREEN_TERMINATED };
