// play screen - resolve a video, then stream it with the simple-lib-av engine.
//
// Both stream urls are handed straight to the player: simple-lib-av opens each through
// openHttpStream (the http module), so each demuxer reads the moov and then each sample
// on demand by HTTP range - nothing is downloaded in full. Adaptive picks are split: a
// video-only stream plus an audio-only stream, each its own independent http stream.
//
// Follows file-manager's video overlay: the open work runs on a worker
// (createVideoPlayer does blocking network I/O and must stay off the UI thread),
// the UI thread adopts the built player and pulls frames each render frame.

#include "screens/play.h"
#include "extractor.h"
#include "stream-select.h"   // pickBestVideo / pickBestAudio (shared with download)

#include "gfx.h"
#include "colors.h"
#include "pad.h"
#include "font.h"
#include "ui/label.h"
#include "ui/image.h"
#include "sprite-regions.h"     // generated by sprite-packer (speaker icon)
#include "button-repeat.h"     // left/right scrub auto-repeat
#include "thread.h"
#include "screen-manager.h"
#include "string-utilities.h"   // strCopy

#include "video-player.h"
#include "audio.h"              // setAudioPcmFeedVolume
#include "storage.h"            // resume position (get/setWatchedPosition)
#include "sponsorblock.h"       // skip segments (auto-skip + seek-bar marks)
#include "dbg.h"                // logInfo/logError (bridge)

#include <string.h>
#include <stdlib.h>
#include <stdio.h>              // snprintf (stats overlay)
#include <sys/sys_time.h>       // sys_time_get_system_time (fps measure)

// volume meter (file-manager's video overlay, pills in youtube red): up/down step it with
// auto-repeat; the pill column + number + speaker icon auto-hide after the last change.
#define VOLUME_PILLS      15
#define VOLUME_DEFAULT    12
#define VOLUME_VISIBLE_US 2500000ULL
#define VOL_NUM_SIZE      22
#define VOL_PILL_W        31
#define VOL_PILL_H        10
#define VOL_PILL_PITCH    19
#define VOL_SPEAKER_W     32
#define VOL_SPEAKER_H     29
#define VOL_SPEAKER_GAP   22
#define COLOR_PILL_EMPTY  0x33FFFFFFu
#define COLOR_PILL_FILL   0xFFFF0000u   // youtube red, matches the seek-bar fill

// seek controls (bar + time) show on activity / pause, then auto-hide. left/right scrub the target
// instantly; the engine seek (a decoder flush + fragment reload each time) fires once input goes quiet.
#define SEEK_STEP_SECONDS   5.0f
#define SEEK_APPLY_IDLE_US  400000ULL
#define CONTROLS_VISIBLE_US 3000000ULL
#define SKIP_NOTICE_US      2000000ULL   // how long the "Skipped ..." toast stays up

// description overlay: SELECT pauses the video and shows the description full-screen; up/down scroll it.
#define DESCRIPTION_MARGIN_X    120
#define DESCRIPTION_MARGIN_Y    80
#define DESCRIPTION_TEXT_SIZE   24
#define DESCRIPTION_SCROLL_STEP 40

// the video to play, set by playVideo() before the screen is pushed. defaults to
// a short public clip so pushing the screen directly still does something.
static char requestedInput[256] = "jNQXAC9IVRw";   // "Me at the zoo"

typedef enum { STAGE_LOADING, STAGE_FAILED, STAGE_PLAYING } Stage;

static struct {
   volatile Stage   stage;
   char             message[128];     // failure reason (worker writes, UI reads)
   VideoPlayer     *pendingPlayer;    // built by the worker, adopted by the UI thread
   volatile int     workerDone;
   int              threadActive;
   sys_ppu_thread_t workerTid;
   VideoPlayer     *player;
   int              screenW, screenH;
   int              firstFrameSeen;   // a real frame has been presented (loading status ends, save is safe)
   int              showStats;        // SELECT toggles a debug overlay
   char             title[256];        // resolved video title (worker sets, UI reads after adoption)
   char             description[2048]; // resolved video description (worker sets, UI reads after adoption)

   // description overlay: opening pauses the video (if it wasn't already); closing only resumes when the
   // pause was ours. the text is rasterised once, on first open, into one tall texture that up/down scroll.
   int              descriptionVisible;
   int              descriptionRendered;
   int              descriptionPausedByUs;
   int              descriptionScroll;   // pixels scrolled down into the text
   int              vidItag, vidW, vidH, vidFps, audItag;   // picked formats (worker sets, UI reads)
   int              isLive;           // a live stream: no duration, no resume/save, no seek
   const uint8_t   *lastFrame;        // fps measure: a changed pointer means a newly presented frame
   int              framesThisSecond, measuredFps;
   uint64_t         fpsTickUs;

   // seek: the UI owns the scrub target so the bar moves instantly; the engine seek is deferred until
   // the input goes quiet (each apply costs a decoder flush + fragment reload)
   int              seeking;
   float            seekTarget;
   uint64_t         lastSeekInputUs;
   uint64_t         controlsShownUs;   // last activity, for the bar/time auto-hide
   uint64_t         volumeShownUs;     // last volume change, for the meter auto-hide

   // sponsorblock: fetched on a side thread (in parallel with resolve/open), then auto-skipped during
   // playback and drawn on the seek bar. sbReady goes up once the thread is reaped and segments are safe.
   SponsorSegments  sb;
   volatile int     sbWorkerDone;
   int              sbThreadActive, sbReady;
   sys_ppu_thread_t sbWorkerTid;
   uint64_t         skipNoticeUs;      // brief "Skipped ..." toast timer (0 = hidden)
} state;

#define STAT_LINES 4

static Font  font;
static Label statusLabel;
static Label statLabels[STAT_LINES];
static Label timeLeftLabel, timeRightLabel;   // seek bar: current time (left) / total (right)
static Label skipNoticeLabel;                 // brief "Skipped ..." toast after an auto-skip
static Label titleLabel;                      // video title, top-left while the seek bar is up
static Label volNumLabel;                     // volume number above the pill column
static TextTexture descriptionTexture;        // whole description as one tall texture (scrolled by draw)

// volume level (0..VOLUME_PILLS) kept outside `state` so it survives across videos, like file-manager's.
static int volumeLevel = VOLUME_DEFAULT;

// the packed sprite sheet, loaded once for the app's lifetime (only the speaker icon lives in it)
static GfxTexture spriteSheet;
static int spriteSheetLoadTried;
static Image speakerImage;
static uint64_t playRequestUs;   // TEMP: set when the user picks a video, to time the WHOLE select->picture path

static void fail(const char *reason)
{
   logError("[yt] play failed: %s\n", reason);
   strCopy(state.message, sizeof state.message, reason);
   __sync_synchronize();   // publish message before the UI thread sees STAGE_FAILED
   state.stage = STAGE_FAILED;
}

static void worker(uint64_t arg)
{
   (void)arg;
   uint64_t tPlayStart = sys_time_get_system_time();   // TEMP: full resume-path timing (resolve -> open -> seek)
   logInfo("[yt] diag worker started %llums after select\n", (unsigned long long)((tPlayStart - playRequestUs) / 1000));   // TEMP
   StreamInfo *info = malloc(sizeof *info);   // ~50 KB, too big for the stack
   const Extractor *extractor = findExtractor(requestedInput);
   if (!info || !extractor) { fail("unrecognised link or id"); goto done; }

   // resolve (stage stays STAGE_LOADING, set by initPlay's memset, until we adopt or fail)
   if (extractor->extract(requestedInput, info) != 0 || info->formatCount == 0) { fail("resolve failed"); goto done; }
   strCopy(state.title, sizeof state.title, info->title);
   strCopy(state.description, sizeof state.description, info->description);
   logInfo("[yt] diag resolve took %llums\n", (unsigned long long)((sys_time_get_system_time() - tPlayStart) / 1000));   // TEMP

   const StreamFormat *video = pickBestVideo(info);
   if (!video) { fail("no playable mp4 video"); goto done; }
   // a muxed pick (itag 18) already carries audio; a video-only pick needs a separate audio track
   const StreamFormat *audio = video->hasAudio ? NULL : pickBestAudio(info);
   logInfo("[yt] play video itag %d %dx%d %s, audio itag %d\n", video->itag, video->width, video->height,
           video->hasAudio ? "muxed" : "video-only", audio ? audio->itag : (video->hasAudio ? video->itag : 0));

   state.vidItag = video->itag; state.vidW = video->width; state.vidH = video->height; state.vidFps = video->fps;
   state.audItag = audio ? audio->itag : (video->hasAudio ? video->itag : 0);
   state.isLive = video->isLiveSegmented;

   // open the decoder: both streams ride the http module by range request. an audio open
   // failure inside the player just means silent playback. NULL if it can't be demuxed/decoded.
   uint64_t tBeforeOpen = sys_time_get_system_time();   // TEMP
   state.pendingPlayer = createVideoPlayerSplit(video->url, audio ? audio->url : NULL, allocGfxVideoBuffer, freeGfxVideoBuffer);
   if (!state.pendingPlayer) { fail("couldn't open stream"); goto done; }
   logInfo("[yt] diag open both streams took %llums (total since play %llums)\n",   // TEMP
           (unsigned long long)((sys_time_get_system_time() - tBeforeOpen) / 1000),
           (unsigned long long)((sys_time_get_system_time() - tPlayStart) / 1000));

   // resume where we left off. seekVideoPlayer only posts the target; the decode thread does the
   // reconnect + fragment reload. drawPlay keeps the "Loading..." status up until the first frame is
   // presented, so that reload is covered rather than showing a black screen. storage returns 0 for a
   // typed url (never a history key), so this no-ops for anything but a bare videoId.
   {
      int resumeAt = state.isLive ? 0 : getWatchedPosition(requestedInput);
      float duration = getVideoDurationSeconds(state.pendingPlayer);
      if (resumeAt > 3 && (duration <= 0 || resumeAt < duration - 10)) seekVideoPlayer(state.pendingPlayer, (float)resumeAt);
   }

done:
   free(info);
   __sync_synchronize();
   state.workerDone = 1;
   exitThread();
}

// a bare 11-char videoId (not a typed url) is what SponsorBlock and history key on; typed urls no-op.
static int isBareVideoId(const char *input)
{
   return input[0] && !strchr(input, '/') && !strchr(input, ':');
}

// fetch skip segments in parallel with resolve/open, so they cost no startup latency.
static void sponsorWorker(uint64_t arg)
{
   (void)arg;
   fetchSponsorSegments(requestedInput, &state.sb);
   __sync_synchronize();
   state.sbWorkerDone = 1;
   exitThread();
}

void playVideo(const char *input)
{
   strCopy(requestedInput, sizeof requestedInput, input);
   playRequestUs = sys_time_get_system_time();   // TEMP: start of the true perceived resume
   pushScreen(&playScreen);
}

static void initPlay(void)
{
   memset(&state, 0, sizeof state);
   state.screenW = getGfxScreenWidth();
   state.screenH = getGfxScreenHeight();

   font = openSystemFont(FONT_POP);
   initLabel(&statusLabel, &font, 0, 0, 1400, AUTO, 28, COLOR_SLATE_100, TEXT_NOWRAP, "");
   for (int i = 0; i < STAT_LINES; i++)
      initLabel(&statLabels[i], &font, 0, 0, 600, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");
   initLabel(&timeLeftLabel,  &font, 0, 0, 200, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");
   initLabel(&timeRightLabel, &font, 0, 0, 200, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");
   initLabel(&skipNoticeLabel, &font, 0, 0, 400, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP, "");
   initLabel(&titleLabel, &font, 0, 0, 1100, AUTO, 22, COLOR_SLATE_100, TEXT_NOWRAP_ELLIPSIS, "");
   initLabel(&volNumLabel, &font, 0, 0, 80, AUTO, VOL_NUM_SIZE, COLOR_SLATE_100, TEXT_NOWRAP, "");

   if (!spriteSheetLoadTried) {
      spriteSheetLoadTried = 1;
      spriteSheet = loadGfxTexture("/dev_hdd0/game/YOPLAYER1/USRDIR/sprites.png");
      if (spriteSheet.w == 0) logWarn("[yt] sprite sheet missing, no speaker icon\n");
   }
   initImage(&speakerImage, spriteSheet, 0, 0, VOL_SPEAKER_W, VOL_SPEAKER_H, spriteRegions[SPRITE_SPEAKER], GFX_FILTER_LINEAR);

   state.threadActive = (spawnJoinableThread(&state.workerTid, worker, 0,
                         THREAD_PRIORITY_DEFAULT, THREAD_STACK_SIZE_64KB, "yt-play") == 0);
   if (!state.threadActive) fail("couldn't start worker");

   if (isBareVideoId(requestedInput))
      state.sbThreadActive = (spawnJoinableThread(&state.sbWorkerTid, sponsorWorker, 0,
                              THREAD_PRIORITY_DEFAULT, THREAD_STACK_SIZE_64KB, "yt-sponsor") == 0);
}

static void showControls(void) { state.controlsShownUs = sys_time_get_system_time(); }

// steps the volume and (re)shows the meter; the number label rasterises here, off the draw path
static void changeVolume(int delta)
{
   int level = volumeLevel + delta;
   if (level < 0) level = 0;
   if (level > VOLUME_PILLS) level = VOLUME_PILLS;
   volumeLevel = level;
   setAudioPcmFeedVolume((float)level / VOLUME_PILLS);
   char num[8];
   snprintf(num, sizeof num, "%d", level);
   setLabelText(&volNumLabel, num);
   state.volumeShownUs = sys_time_get_system_time();
}

// accumulates a scrub target while left/right is held; the engine seek fires once input goes quiet
static void nudgeSeek(float deltaSeconds, uint64_t nowUs)
{
   if (!state.seeking) { state.seeking = 1; state.seekTarget = getVideoPositionSeconds(state.player); }
   state.seekTarget += deltaSeconds;
   float duration = getVideoDurationSeconds(state.player);
   if (state.seekTarget < 0.0f) state.seekTarget = 0.0f;
   if (duration > 0.0f && state.seekTarget > duration) state.seekTarget = duration;
   state.lastSeekInputUs = nowUs;
   showControls();
}

// left/right scrub, cross toggles pause (restarts if the video ended). only once playing.
static void handlePlaybackInput(void)
{
   uint64_t nowUs = sys_time_get_system_time();

   if (isPadButtonPressed(PAD_BTN_CROSS)) {
      if (isVideoEnded(state.player)) seekVideoPlayer(state.player, 0.0f);
      else setVideoPaused(state.player, !isVideoPaused(state.player));
      showControls();
   }

   // volume: stepped, with auto-repeat while held (works on live streams too)
   static ButtonRepeat volumeRepeat;
   if (isRepeatDue(&volumeRepeat, getPadButtonState(PAD_BTN_UP)))        changeVolume(+1);
   else if (isRepeatDue(&volumeRepeat, getPadButtonState(PAD_BTN_DOWN))) changeVolume(-1);

   if (state.isLive) return;   // a live stream has no seek index; scrubbing would break the segment stream

   static ButtonRepeat seekRepeat;
   if (isRepeatDue(&seekRepeat, getPadButtonState(PAD_BTN_RIGHT)))     nudgeSeek(+SEEK_STEP_SECONDS, nowUs);
   else if (isRepeatDue(&seekRepeat, getPadButtonState(PAD_BTN_LEFT))) nudgeSeek(-SEEK_STEP_SECONDS, nowUs);

   if (state.seeking && nowUs - state.lastSeekInputUs >= SEEK_APPLY_IDLE_US) {
      seekVideoPlayer(state.player, state.seekTarget);
      state.seeking = 0;
   }
}

// jump past the first not-yet-skipped sponsor segment the playhead has entered. one-shot per segment so a
// manual rewind into it doesn't fight the user.
static void autoSkipSponsor(void)
{
   float pos = getVideoPositionSeconds(state.player);
   for (int i = 0; i < state.sb.count; i++) {
      SponsorSegment *segment = &state.sb.segments[i];
      if (segment->skipped || pos < segment->start || pos >= segment->end - 0.2f) continue;
      segment->skipped = 1;
      seekVideoPlayerPast(state.player, segment->end);   // land on the next keyframe after the segment, not before it
      char notice[64];
      snprintf(notice, sizeof notice, "Skipped %s", getSponsorCategoryName(segment->category));
      setLabelText(&skipNoticeLabel, notice);
      state.skipNoticeUs = sys_time_get_system_time();
      showControls();
      return;
   }
}

// SELECT opens the description: pause the video (remembering whether the pause was ours) and rasterise
// the text once, off the draw path, as one tall wrapped texture the draw scrolls through.
static void openDescription(void)
{
   if (!state.descriptionRendered) {
      renderFontRaw(&descriptionTexture, &font, DESCRIPTION_TEXT_SIZE, state.description[0] ? state.description : "No description.",
                    COLOR_SLATE_100, state.screenW - 2 * DESCRIPTION_MARGIN_X, TEXT_WRAP);
      state.descriptionRendered = 1;
   }
   state.descriptionPausedByUs = !isVideoPaused(state.player);
   if (state.descriptionPausedByUs) setVideoPaused(state.player, 1);
   state.descriptionScroll = 0;
   state.descriptionVisible = 1;
}

// while the description is up it owns the pad: SELECT/circle close it (resuming only a pause that was
// ours), up/down scroll. playback input (seek, pause, back-out) is blocked underneath.
static void handleDescriptionInput(void)
{
   if (isPadButtonPressed(PAD_BTN_SELECT) || isPadButtonPressed(PAD_BTN_CIRCLE)) {
      state.descriptionVisible = 0;
      if (state.descriptionPausedByUs) setVideoPaused(state.player, 0);
      return;
   }

   static ButtonRepeat scrollRepeat;
   if (isRepeatDue(&scrollRepeat, getPadButtonState(PAD_BTN_DOWN)))    state.descriptionScroll += DESCRIPTION_SCROLL_STEP;
   else if (isRepeatDue(&scrollRepeat, getPadButtonState(PAD_BTN_UP))) state.descriptionScroll -= DESCRIPTION_SCROLL_STEP;

   int viewHeight = state.screenH - 2 * DESCRIPTION_MARGIN_Y;
   int maxScroll = descriptionTexture.tex.h > viewHeight ? descriptionTexture.tex.h - viewHeight : 0;
   if (state.descriptionScroll > maxScroll) state.descriptionScroll = maxScroll;
   if (state.descriptionScroll < 0) state.descriptionScroll = 0;
}

static void updatePlay(void)
{
   if (state.descriptionVisible) handleDescriptionInput();
   else {
      if (isPadButtonPressed(PAD_BTN_CIRCLE)) { popScreen(); return; }   // back to the results list
      if (isPadButtonPressed(PAD_BTN_R3)) state.showStats = !state.showStats;
      if (isPadButtonPressed(PAD_BTN_SELECT) && state.stage == STAGE_PLAYING && state.player) openDescription();
   }

   // reap the worker once it's done; adopt the player it built
   if (state.workerDone && state.threadActive) {
      joinThread(state.workerTid);
      state.threadActive = 0;
      if (state.pendingPlayer) {
         state.player = state.pendingPlayer;
         state.pendingPlayer = NULL;
         setAudioPcmFeedVolume((float)volumeLevel / VOLUME_PILLS);
         setLabelText(&titleLabel, state.title);   // rasterise once, off the draw path
         state.stage = STAGE_PLAYING;
      }
   }

   // reap the sponsorblock fetch; its segments are safe to read once joined
   if (state.sbWorkerDone && state.sbThreadActive) {
      joinThread(state.sbWorkerTid);
      state.sbThreadActive = 0;
      state.sbReady = 1;
   }

   if (state.stage == STAGE_PLAYING && state.player && !state.descriptionVisible) handlePlaybackInput();
   if (state.sbReady && state.stage == STAGE_PLAYING && state.player && !isVideoPaused(state.player) && !state.seeking)
      autoSkipSponsor();

   // status text: the failure reason, or "Loading..." until playback. setLabelText skips unchanged
   // text, so calling it each frame only rasterises on a real change.
   if (state.stage == STAGE_FAILED) setLabelText(&statusLabel, state.message);
   else if (state.stage != STAGE_PLAYING) setLabelText(&statusLabel, "Loading...");
}

// fits w x h inside the screen preserving aspect ratio; returns the centred rect.
static void letterboxRect(int w, int h, int *dx, int *dy, int *dw, int *dh)
{
   float frameAspect  = (float)w / (float)h;
   float screenAspect = (float)state.screenW / (float)state.screenH;
   if (frameAspect > screenAspect) { *dw = state.screenW; *dh = (int)(state.screenW / frameAspect); }
   else                            { *dh = state.screenH; *dw = (int)(state.screenH * frameAspect); }
   *dx = (state.screenW - *dw) / 2;
   *dy = (state.screenH - *dh) / 2;
}

// measure the real presented frame rate: a changed frame pointer is a new frame; tally them per second.
static void measureFps(const uint8_t *frame)
{
   if (frame && frame != state.lastFrame) { state.framesThisSecond++; state.lastFrame = frame; }
   uint64_t now = sys_time_get_system_time();
   if (now - state.fpsTickUs >= 1000000) { state.measuredFps = state.framesThisSecond; state.framesThisSecond = 0; state.fpsTickUs = now; }
}

// rebuild the overlay lines. setLabelText skips unchanged text, so calling this per frame only
// rasterises when a value actually moves (fps + time once a second).
static void updateStatLabels(void)
{
   char line[96];
   int rate = 0, channels = 0;
   getAudioTrackInfo(state.player, &rate, &channels);
   float pos = getVideoPositionSeconds(state.player), duration = getVideoDurationSeconds(state.player);

   snprintf(line, sizeof line, "Video  itag %d   %dx%d   H.264", state.vidItag, state.vidW, state.vidH);
   setLabelText(&statLabels[0], line);
   snprintf(line, sizeof line, "FPS  %d   (target %d)", state.measuredFps, state.vidFps);
   setLabelText(&statLabels[1], line);
   if (state.audItag) snprintf(line, sizeof line, "Audio  itag %d   AAC %d Hz   %d ch", state.audItag, rate, channels);
   else               strCopy(line, sizeof line, "Audio  none");
   setLabelText(&statLabels[2], line);
   snprintf(line, sizeof line, "Time  %d:%02d / %d:%02d", (int)pos / 60, (int)pos % 60, (int)duration / 60, (int)duration % 60);
   setLabelText(&statLabels[3], line);
}

static void drawStatsOverlay(void)
{
   int x = 40, y = 44, lineHeight = 30;
   fillGfxRectangle(x - 14, y - 12, 500, STAT_LINES * lineHeight + 14, 0xC0000000);
   for (int i = 0; i < STAT_LINES; i++) drawLabelAt(&statLabels[i], x, y + i * lineHeight);
}

// seek bar + time show while scrubbing / paused / ended, else auto-hide after the last activity
static int controlsVisible(void)
{
   if (isVideoPaused(state.player) || isVideoEnded(state.player) || state.seeking) return 1;
   return state.controlsShownUs != 0 && sys_time_get_system_time() - state.controlsShownUs < CONTROLS_VISIBLE_US;
}

static void formatTime(char *buffer, int cap, int seconds)
{
   if (seconds < 0) seconds = 0;
   if (seconds >= 3600) snprintf(buffer, cap, "%d:%02d:%02d", seconds / 3600, (seconds % 3600) / 60, seconds % 60);
   else                 snprintf(buffer, cap, "%d:%02d", seconds / 60, seconds % 60);
}

// paint each sponsor segment onto the bar in its category colour, over the progress fill so it stays
// visible in the already-watched region (as YouTube's SponsorBlock overlay does).
static void drawSponsorSegments(int barLeft, int span, int barTopY, int barH, float duration)
{
   if (duration <= 0.0f) return;
   for (int i = 0; i < state.sb.count; i++) {
      const SponsorSegment *segment = &state.sb.segments[i];
      float startFrac = segment->start / duration, endFrac = segment->end / duration;
      if (startFrac < 0.0f) startFrac = 0.0f;
      if (endFrac > 1.0f) endFrac = 1.0f;
      int segX = barLeft + (int)(startFrac * span);
      int segW = (int)((endFrac - startFrac) * span);
      if (segW < 2) segW = 2;
      fillGfxRectangle(segX, barTopY, segW, barH, getSponsorCategoryColor(segment->category));
   }
}

// a red YouTube-style progress bar low on the screen with current/total time on each side, drawn from
// plain rectangles (no spritesheet), with sponsor segments marked over the fill.
static void drawSeekBar(void)
{
   float duration = getVideoDurationSeconds(state.player);
   float position = state.seeking ? state.seekTarget : getVideoPositionSeconds(state.player);
   float progress = duration > 0.0f ? position / duration : 0.0f;
   if (progress < 0.0f) progress = 0.0f;
   if (progress > 1.0f) progress = 1.0f;

   int barLeft  = (int)(state.screenW * 0.24f);
   int barRight = state.screenW - barLeft;
   int span     = barRight - barLeft;
   int barY     = (int)(state.screenH * 0.94f);
   int barH     = 8;
   int barTopY  = barY - barH / 2;
   int filledW  = (int)(progress * span);

   fillGfxRectangle(barLeft, barTopY, span, barH, 0x66FFFFFF);            // track
   fillGfxRectangle(barLeft, barTopY, filledW, barH, 0xFFFF0000);        // progress (youtube red)
   if (state.sbReady) drawSponsorSegments(barLeft, span, barTopY, barH, duration);
   fillGfxRectangle(barLeft + filledW - 3, barY - 11, 6, 22, 0xFFFFFFFF);   // scrubber handle

   char text[16];
   formatTime(text, sizeof text, (int)position);            setLabelText(&timeLeftLabel, text);
   formatTime(text, sizeof text, (int)(duration + 0.5f));   setLabelText(&timeRightLabel, text);
   drawLabelAt(&timeLeftLabel,  barLeft - 20 - timeLeftLabel.tt.tex.w, barY - timeLeftLabel.tt.tex.h / 2);
   drawLabelAt(&timeRightLabel, barRight + 20, barY - timeRightLabel.tt.tex.h / 2);
}

// the video title, top-left in a duration-badge-style box, shown whenever the seek bar is up.
static void drawTitle(void)
{
   if (titleLabel.tt.tex.w == 0) return;
   int badgeW = titleLabel.tt.tex.w + 12, badgeH = titleLabel.tt.tex.h + 8;
   fillGfxRectangle(40, 32, badgeW, badgeH, 0xCC000000);
   drawLabelAt(&titleLabel, 46, 36);
}

// the pill-column volume meter: filled pills bottom-up in red, the level number above, the speaker
// icon below, auto-hides
static void drawVolumeMeter(void)
{
   if (state.volumeShownUs == 0 || sys_time_get_system_time() - state.volumeShownUs >= VOLUME_VISIBLE_US) return;
   int pillX   = (int)(state.screenW * 0.07f);
   int bottomY = state.screenH / 2 + (VOLUME_PILLS - 1) * VOL_PILL_PITCH / 2;   // column centred vertically
   for (int i = 0; i < VOLUME_PILLS; i++)
      fillGfxRectangle(pillX, bottomY - i * VOL_PILL_PITCH, VOL_PILL_W, VOL_PILL_H, i < volumeLevel ? COLOR_PILL_FILL : COLOR_PILL_EMPTY);
   int topPillY = bottomY - (VOLUME_PILLS - 1) * VOL_PILL_PITCH;
   drawLabelAt(&volNumLabel, pillX + VOL_PILL_W / 2 - volNumLabel.tt.tex.w / 2, topPillY - VOL_NUM_SIZE - 14);
   if (spriteSheet.w > 0) drawImageAt(&speakerImage, pillX + VOL_PILL_W / 2 - VOL_SPEAKER_W / 2, bottomY + VOL_PILL_H + VOL_SPEAKER_GAP);
}

// the description over the whole video: a semi-transparent black layer, then the slice of the text
// texture the scroll position selects (the texture is drawn through a window, so no clipping is needed).
static void drawDescription(void)
{
   fillGfxRectangle(0, 0, state.screenW, state.screenH, 0xE6000000);   // 90% opaque black
   if (descriptionTexture.tex.w == 0) return;

   int viewHeight = state.screenH - 2 * DESCRIPTION_MARGIN_Y;
   int visibleHeight = descriptionTexture.tex.h - state.descriptionScroll;
   if (visibleHeight > viewHeight) visibleHeight = viewHeight;
   if (visibleHeight <= 0) return;

   float sliceTop    = (float)state.descriptionScroll / descriptionTexture.tex.h;
   float sliceBottom = (float)(state.descriptionScroll + visibleHeight) / descriptionTexture.tex.h;
   drawGfxTexture(DESCRIPTION_MARGIN_X, DESCRIPTION_MARGIN_Y, descriptionTexture.tex.w, visibleHeight,
                  descriptionTexture.tex, 0.0f, sliceTop, 1.0f, sliceBottom, 0xFFFFFFFF, GFX_FILTER_NEAREST);
}

// the "Skipped ..." toast, centred just above the seek bar for a moment after an auto-skip.
static void drawSkipNotice(void)
{
   if (state.skipNoticeUs == 0 || sys_time_get_system_time() - state.skipNoticeUs >= SKIP_NOTICE_US) return;
   int barY = (int)(state.screenH * 0.94f);
   int x = state.screenW / 2 - skipNoticeLabel.tt.tex.w / 2;
   int y = barY - 60;
   fillGfxRectangle(x - 14, y - 6, skipNoticeLabel.tt.tex.w + 28, skipNoticeLabel.tt.tex.h + 12, 0xC0000000);
   drawLabelAt(&skipNoticeLabel, x, y);
}

static void drawPlay(void)
{
   fillGfxRectangle(0, 0, state.screenW, state.screenH, COLOR_BLACK);   // letterbox bars read as black, not slate

   const uint8_t *frame = NULL;
   if (state.player) {
      int w, h;
      frame = getVideoFrame(state.player, &w, &h);
      if (frame) {
         if (!state.firstFrameSeen) {
            logInfo("[yt] diag select-to-picture %llums\n", (unsigned long long)((sys_time_get_system_time() - playRequestUs) / 1000));   // TEMP
            showControls();   // bring the HUD (seek bar + title) up as playback starts; it auto-hides as usual
         }
         state.firstFrameSeen = 1;
         int dx, dy, dw, dh;
         letterboxRect(w, h, &dx, &dy, &dw, &dh);
         drawGfxYuvFrame(dx, dy, dw, dh, frame, w, h);
      }
      measureFps(frame);
      if (state.showStats && frame) { updateStatLabels(); drawStatsOverlay(); }
      if (state.stage == STAGE_PLAYING && !state.isLive && controlsVisible()) { drawSeekBar(); drawTitle(); }   // live has no timeline
      if (state.stage == STAGE_PLAYING) { drawSkipNotice(); drawVolumeMeter(); }
      if (state.descriptionVisible) drawDescription();
   }

   // until the first frame is presented (open, then the async resume seek's reload) keep the loading
   // status up instead of a black screen; with no player this shows the failure message.
   if (!state.firstFrameSeen)
      drawLabelAt(&statusLabel, state.screenW / 2 - statusLabel.tt.tex.w / 2, state.screenH / 2 - 14);
}

static void termPlay(void)
{
   if (state.threadActive) { joinThread(state.workerTid); state.threadActive = 0; }
   if (state.sbThreadActive) { joinThread(state.sbWorkerTid); state.sbThreadActive = 0; }   // usually already done
   // save the resume position on the way out; a finished video is saved as 0 so it restarts next time.
   // only once a frame has actually played: a failed open or a resume seek that never landed must not
   // clobber a good saved position with 0. storage ignores non-id keys, so typed urls no-op.
   if (state.player && state.firstFrameSeen && !state.isLive)
      setWatchedPosition(requestedInput, isVideoEnded(state.player) ? 0 : (int)getVideoPositionSeconds(state.player));
   if (state.player || state.pendingPlayer) finishGfx();   // RSX may still be sampling a frame buffer
   if (state.player) { destroyVideoPlayer(state.player); state.player = NULL; }
   if (state.pendingPlayer) { destroyVideoPlayer(state.pendingPlayer); state.pendingPlayer = NULL; }
   freeLabel(&statusLabel);
   for (int i = 0; i < STAT_LINES; i++) freeLabel(&statLabels[i]);
   freeLabel(&timeLeftLabel);
   freeLabel(&timeRightLabel);
   freeLabel(&skipNoticeLabel);
   freeLabel(&titleLabel);
   freeLabel(&volNumLabel);
   freeTextTexture(&descriptionTexture);
   closeFont(&font);
}

Screen playScreen = { initPlay, NULL, updatePlay, drawPlay, NULL, termPlay, SCREEN_TERMINATED };
