#pragma once

// auto-generated by sprite-packer - do not edit

#include "gfx.h"

enum SpriteId {
    SPRITE_GENERIC,
    SPRITE_FOLDER,
    SPRITE_EXECUTABLE,
    SPRITE_IMAGE,
    SPRITE_VIDEO,
    SPRITE_TEXT,
    SPRITE_PACKAGE,
    SPRITE_DOCUMENT,
    SPRITE_COMPRESSED,
    SPRITE_AUDIO,
    SPRITE_DISC_ISO,
    SPRITE_DATABASE,
    SPRITE_HOVER,
    SPRITE_CHECKBOX_CHECKED,
    SPRITE_CHECKBOX,
    SPRITE_CHEVRON,
    SPRITE_SEPARATOR
};

static const SpriteRegion spriteRegions[17] = {
    [SPRITE_GENERIC]          = {    0,    0,   50,   60 },
    [SPRITE_FOLDER]           = {   51,    0,   50,   60 },
    [SPRITE_EXECUTABLE]       = {  102,    0,   50,   60 },
    [SPRITE_IMAGE]            = {  153,    0,   50,   60 },
    [SPRITE_VIDEO]            = {  204,    0,   50,   60 },
    [SPRITE_TEXT]             = {    0,   61,   50,   60 },
    [SPRITE_PACKAGE]          = {   51,   61,   50,   60 },
    [SPRITE_DOCUMENT]         = {  102,   61,   50,   60 },
    [SPRITE_COMPRESSED]       = {  153,   61,   50,   60 },
    [SPRITE_AUDIO]            = {  204,   61,   50,   60 },
    [SPRITE_DISC_ISO]         = {    0,  122,   50,   60 },
    [SPRITE_DATABASE]         = {   51,  122,   50,   60 },
    [SPRITE_HOVER]            = {  102,  122,   33,   58 },
    [SPRITE_CHECKBOX_CHECKED] = {  136,  122,   31,   30 },
    [SPRITE_CHECKBOX]         = {  168,  122,   30,   30 },
    [SPRITE_CHEVRON]          = {  199,  122,    7,   12 },
    [SPRITE_SEPARATOR]        = {  207,  122,    3,    2 },
};

#define SPRITE_FULL ((SpriteRegion){0})
