#pragma once

// auto-generated by sprite-packer - do not edit

#include "gfx.h"

enum SpriteId {
    SPRITE_HOVER_MENU,
    SPRITE_FOLDER,
    SPRITE_GENERIC_MULTI,
    SPRITE_DOCUMENT,
    SPRITE_EXECUTABLE,
    SPRITE_GENERIC,
    SPRITE_PACKAGE,
    SPRITE_TEXT,
    SPRITE_VIDEO,
    SPRITE_IMAGE,
    SPRITE_DATABASE,
    SPRITE_COMPRESSED,
    SPRITE_AUDIO,
    SPRITE_DISC_ISO,
    SPRITE_HOVER,
    SPRITE_RENAME,
    SPRITE_NEW_FILE,
    SPRITE_PROPERTIES,
    SPRITE_PASTE,
    SPRITE_NEW_DIR,
    SPRITE_CUT,
    SPRITE_DELETE,
    SPRITE_COPY,
    SPRITE_EDIT,
    SPRITE_CHECKBOX_CHECKED,
    SPRITE_CHECKBOX,
    SPRITE_CHEVRON,
    SPRITE_SEPARATOR
};

static const SpriteRegion spriteRegions[28] = {
    [SPRITE_HOVER_MENU]       = {    0,    0,   33,   96 },
    [SPRITE_FOLDER]           = {   34,    0,   50,   60 },
    [SPRITE_GENERIC_MULTI]    = {   85,    0,   50,   60 },
    [SPRITE_DOCUMENT]         = {  136,    0,   50,   60 },
    [SPRITE_EXECUTABLE]       = {  187,    0,   50,   60 },
    [SPRITE_GENERIC]          = {  238,    0,   50,   60 },
    [SPRITE_PACKAGE]          = {  289,    0,   50,   60 },
    [SPRITE_TEXT]             = {  340,    0,   50,   60 },
    [SPRITE_VIDEO]            = {  391,    0,   50,   60 },
    [SPRITE_IMAGE]            = {  442,    0,   50,   60 },
    [SPRITE_DATABASE]         = {    0,   97,   50,   60 },
    [SPRITE_COMPRESSED]       = {   51,   97,   50,   60 },
    [SPRITE_AUDIO]            = {  102,   97,   50,   60 },
    [SPRITE_DISC_ISO]         = {  153,   97,   50,   60 },
    [SPRITE_HOVER]            = {  204,   97,   33,   58 },
    [SPRITE_RENAME]           = {  238,   97,   48,   48 },
    [SPRITE_NEW_FILE]         = {  287,   97,   48,   48 },
    [SPRITE_PROPERTIES]       = {  336,   97,   48,   48 },
    [SPRITE_PASTE]            = {  385,   97,   48,   48 },
    [SPRITE_NEW_DIR]          = {  434,   97,   48,   48 },
    [SPRITE_CUT]              = {    0,  158,   48,   48 },
    [SPRITE_DELETE]           = {   49,  158,   48,   48 },
    [SPRITE_COPY]             = {   98,  158,   48,   48 },
    [SPRITE_EDIT]             = {  147,  158,   48,   48 },
    [SPRITE_CHECKBOX_CHECKED] = {  196,  158,   31,   30 },
    [SPRITE_CHECKBOX]         = {  228,  158,   30,   30 },
    [SPRITE_CHEVRON]          = {  259,  158,    7,   12 },
    [SPRITE_SEPARATOR]        = {  267,  158,    3,    2 },
};

#define SPRITE_FULL ((SpriteRegion){0})
